module.exports = {
    UPDATE_LOCAL_STATE: 'UPDATE_LOCAL_STATE',
    UPDATE_CONTRACTOR_VIEW_STATE: 'UPDATE_CONTRACTOR_VIEW_STATE',
    DELETE_CONTRACTOR: 'DELETE_CONTRACTOR',
    ADD_CONTRACTOR: 'ADD_CONTRACTOR'
};
