module.exports = {
    REQUEST_CONTRACTORS: 'REQUEST_CONTRACTORS',
    RECEIVE_CONTRACTORS: 'RECEIVE_CONTRACTORS',
    UPDATE_CONTRACTOR_VIEW_STATE: 'UPDATE_CONTRACTOR_VIEW_STATE',
    DELETE_CONTRACTOR: 'DELETE_CONTRACTOR'
};
